function t = topLevel()
    %iris
    [rTrainX, rTrainY, trainX, trainY, testX, testY, crossX, crossY] = irisFunction();
    Iris50 = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY)) ...
            ,testX, testY)

    Iris10 = ...
    testing(training(rTrainX, rTrainY, ...
                    crossValidation(rTrainX, rTrainY, crossX, crossY)) ...
            ,testX, testY)
        
    %wine
    [trainX, trainY, testX, testY, crossX, crossY] = wineFunction();
    misclassificationsWine = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY)) ...
            ,testX, testY);
    misclassificationsWine

%     [trainX, trainY, testX, testY, crossX, crossY] = caesarianFunction();
%     misclassificationsWine = ...
%     testing(training(trainX, trainY, ...
%                     crossValidation(trainX, trainY, crossX, crossY) ...
%             ,testX, testY);
% 
%     [trainX, trainY, testX, testY, crossX, crossY] = fertilityFunction();
%     misclassificationsWine = ...
%     testing(training(trainX, trainY, ...
%                     crossValidation(trainX, trainY, crossX, crossY) ...
%             ,testX, testY);

    