function t = topLevel()
    [trainX, trainY, testX, testY, crossX, crossY] = irisFunction();
    misclassificationsIris = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY) ...
            testX, testY);
    
    [trainX, trainY, testX, testY, crossX, crossY] = wineFunction();
    misclassificationsWine = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY) ...
            testX, testY);

    [trainX, trainY, testX, testY, crossX, crossY] = caesarianFunction();
    misclassificationsWine = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY) ...
            testX, testY);

    [trainX, trainY, testX, testY, crossX, crossY] = fertilityFunction();
    misclassificationsWine = ...
    testing(training(trainX, trainY, ...
                    crossValidation(trainX, trainY, crossX, crossY) ...
            testX, testY);

    